"""AuthService gRPC servicer — implements ValidateKey from auth.proto.

The Go gateway calls ValidateKey when both its in-process LRU and Redis miss.
We look up the key by SHA-256 lookup hash via the UoW and translate the
domain entity back to the proto response.
"""
from __future__ import annotations

from typing import TYPE_CHECKING, Any

from app.shared.logging import get_logger
from app.repository.database import get_session_factory
from app.repository.uow import SqlUnitOfWork

# TODO: regenerated by `make proto` — these stubs do not yet exist on disk.
if TYPE_CHECKING:  # pragma: no cover
    from app.repository.grpc.gen.auth.v1 import auth_pb2, auth_pb2_grpc  # noqa: F401

try:
    from app.repository.grpc.gen.auth.v1 import auth_pb2, auth_pb2_grpc  # type: ignore[import-not-found]

    _BASE = auth_pb2_grpc.AuthServiceServicer
except ImportError:
    auth_pb2 = None  # type: ignore[assignment]
    _BASE = object  # type: ignore[assignment,misc]

_log = get_logger(__name__)


class AuthServicer(_BASE):  # type: ignore[misc,valid-type]
    """Servicer that resolves API keys via the UoW."""

    async def ValidateKey(self, request: Any, context: Any) -> Any:  # noqa: N802
        if auth_pb2 is None:  # pragma: no cover — codegen not yet run
            raise RuntimeError("auth_pb2 not generated — run `make proto`")
        uow = SqlUnitOfWork(get_session_factory())
        async with uow:
            key = await uow.api_keys.find_by_lookup_hash(request.key_hash)
            if key is None:
                return auth_pb2.ValidateKeyResponse(valid=False, revocation_reason="unknown_key")
            try:
                key.assert_usable()
            except Exception as exc:  # noqa: BLE001
                return auth_pb2.ValidateKeyResponse(valid=False, revocation_reason=str(exc))
            balance = await uow.credits.get_for_update(key.org_id)

        budget = auth_pb2.BudgetPolicy(
            remaining_credits=float(balance.usable.amount),
            daily_cap=float(balance.daily_cap or 0),
            monthly_cap=float(balance.monthly_cap or 0),
            hard_stop=balance.hard_stop,
        )
        return auth_pb2.ValidateKeyResponse(
            valid=True,
            key_id=str(key.id),
            org_id=str(key.org_id),
            user_id=str(key.user_id),
            allowed_models=list(key.allowed_models),
            denied_models=list(key.denied_models),
            budget=budget,
        )

    async def RevokeKey(self, request: Any, context: Any) -> Any:  # noqa: N802
        if auth_pb2 is None:  # pragma: no cover
            raise RuntimeError("auth_pb2 not generated — run `make proto`")
        from uuid import UUID

        uow = SqlUnitOfWork(get_session_factory())
        async with uow:
            await uow.api_keys.revoke(UUID(request.key_id), reason=request.reason or "rpc_revoke")
            await uow.commit()
        return auth_pb2.RevokeKeyResponse(ok=True)
