// Usage events emitted by the Go gateway after every completed request.
// Consumed by the Python metering worker via NATS JetStream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: usage/v1/usage.proto

package usagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsageEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // ULID
	EmittedAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=emitted_at,json=emittedAt,proto3" json:"emitted_at,omitempty"`
	TraceId          string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId           string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	KeyId            string                 `protobuf:"bytes,7,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Model            string                 `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	Provider         string                 `protobuf:"bytes,9,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderEndpoint string                 `protobuf:"bytes,10,opt,name=provider_endpoint,json=providerEndpoint,proto3" json:"provider_endpoint,omitempty"` // region-specific identifier
	Tokens           *TokenCounts           `protobuf:"bytes,11,opt,name=tokens,proto3" json:"tokens,omitempty"`
	CostUsd          float64                `protobuf:"fixed64,12,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"` // gateway estimate; backend re-computes
	LatencyMs        uint32                 `protobuf:"varint,13,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	StatusCode       uint32                 `protobuf:"varint,14,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	FinishReason     string                 `protobuf:"bytes,15,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // stop | length | tool_calls | content_filter | error
	CacheHit         bool                   `protobuf:"varint,16,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	CacheLayer       string                 `protobuf:"bytes,17,opt,name=cache_layer,json=cacheLayer,proto3" json:"cache_layer,omitempty"` // "" | l1_exact | l2_semantic
	FailoverUsed     bool                   `protobuf:"varint,18,opt,name=failover_used,json=failoverUsed,proto3" json:"failover_used,omitempty"`
	RetryCount       uint32                 `protobuf:"varint,19,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageEvent) Reset() {
	*x = UsageEvent{}
	mi := &file_usage_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageEvent) ProtoMessage() {}

func (x *UsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageEvent.ProtoReflect.Descriptor instead.
func (*UsageEvent) Descriptor() ([]byte, []int) {
	return file_usage_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *UsageEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UsageEvent) GetEmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EmittedAt
	}
	return nil
}

func (x *UsageEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *UsageEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UsageEvent) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *UsageEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UsageEvent) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UsageEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UsageEvent) GetProviderEndpoint() string {
	if x != nil {
		return x.ProviderEndpoint
	}
	return ""
}

func (x *UsageEvent) GetTokens() *TokenCounts {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *UsageEvent) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *UsageEvent) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UsageEvent) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UsageEvent) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *UsageEvent) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *UsageEvent) GetCacheLayer() string {
	if x != nil {
		return x.CacheLayer
	}
	return ""
}

func (x *UsageEvent) GetFailoverUsed() bool {
	if x != nil {
		return x.FailoverUsed
	}
	return false
}

func (x *UsageEvent) GetRetryCount() uint32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

type TokenCounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         uint32                 `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	Output        uint32                 `protobuf:"varint,2,opt,name=output,proto3" json:"output,omitempty"`
	CachedInput   uint32                 `protobuf:"varint,3,opt,name=cached_input,json=cachedInput,proto3" json:"cached_input,omitempty"` // provider-side prompt caching
	Reasoning     uint32                 `protobuf:"varint,4,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                        // o-series, DeepSeek-R1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCounts) Reset() {
	*x = TokenCounts{}
	mi := &file_usage_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCounts) ProtoMessage() {}

func (x *TokenCounts) ProtoReflect() protoreflect.Message {
	mi := &file_usage_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCounts.ProtoReflect.Descriptor instead.
func (*TokenCounts) Descriptor() ([]byte, []int) {
	return file_usage_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *TokenCounts) GetInput() uint32 {
	if x != nil {
		return x.Input
	}
	return 0
}

func (x *TokenCounts) GetOutput() uint32 {
	if x != nil {
		return x.Output
	}
	return 0
}

func (x *TokenCounts) GetCachedInput() uint32 {
	if x != nil {
		return x.CachedInput
	}
	return 0
}

func (x *TokenCounts) GetReasoning() uint32 {
	if x != nil {
		return x.Reasoning
	}
	return 0
}

var File_usage_v1_usage_proto protoreflect.FileDescriptor

const file_usage_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x14usage/v1/usage.proto\x12\x13openrouter.usage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x05\n" +
	"\n" +
	"UsageEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x129\n" +
	"\n" +
	"emitted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\temittedAt\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x15\n" +
	"\x06key_id\x18\a \x01(\tR\x05keyId\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\t \x01(\tR\bprovider\x12+\n" +
	"\x11provider_endpoint\x18\n" +
	" \x01(\tR\x10providerEndpoint\x128\n" +
	"\x06tokens\x18\v \x01(\v2 .openrouter.usage.v1.TokenCountsR\x06tokens\x12\x19\n" +
	"\bcost_usd\x18\f \x01(\x01R\acostUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\r \x01(\rR\tlatencyMs\x12\x1f\n" +
	"\vstatus_code\x18\x0e \x01(\rR\n" +
	"statusCode\x12#\n" +
	"\rfinish_reason\x18\x0f \x01(\tR\ffinishReason\x12\x1b\n" +
	"\tcache_hit\x18\x10 \x01(\bR\bcacheHit\x12\x1f\n" +
	"\vcache_layer\x18\x11 \x01(\tR\n" +
	"cacheLayer\x12#\n" +
	"\rfailover_used\x18\x12 \x01(\bR\ffailoverUsed\x12\x1f\n" +
	"\vretry_count\x18\x13 \x01(\rR\n" +
	"retryCount\"|\n" +
	"\vTokenCounts\x12\x14\n" +
	"\x05input\x18\x01 \x01(\rR\x05input\x12\x16\n" +
	"\x06output\x18\x02 \x01(\rR\x06output\x12!\n" +
	"\fcached_input\x18\x03 \x01(\rR\vcachedInput\x12\x1c\n" +
	"\treasoning\x18\x04 \x01(\rR\treasoningBBZ@github.com/openrouter/gateway-go/internal/proto/usage/v1;usagev1b\x06proto3"

var (
	file_usage_v1_usage_proto_rawDescOnce sync.Once
	file_usage_v1_usage_proto_rawDescData []byte
)

func file_usage_v1_usage_proto_rawDescGZIP() []byte {
	file_usage_v1_usage_proto_rawDescOnce.Do(func() {
		file_usage_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_usage_v1_usage_proto_rawDesc), len(file_usage_v1_usage_proto_rawDesc)))
	})
	return file_usage_v1_usage_proto_rawDescData
}

var file_usage_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_usage_v1_usage_proto_goTypes = []any{
	(*UsageEvent)(nil),            // 0: openrouter.usage.v1.UsageEvent
	(*TokenCounts)(nil),           // 1: openrouter.usage.v1.TokenCounts
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_usage_v1_usage_proto_depIdxs = []int32{
	2, // 0: openrouter.usage.v1.UsageEvent.emitted_at:type_name -> google.protobuf.Timestamp
	1, // 1: openrouter.usage.v1.UsageEvent.tokens:type_name -> openrouter.usage.v1.TokenCounts
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_usage_v1_usage_proto_init() }
func file_usage_v1_usage_proto_init() {
	if File_usage_v1_usage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usage_v1_usage_proto_rawDesc), len(file_usage_v1_usage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_usage_v1_usage_proto_goTypes,
		DependencyIndexes: file_usage_v1_usage_proto_depIdxs,
		MessageInfos:      file_usage_v1_usage_proto_msgTypes,
	}.Build()
	File_usage_v1_usage_proto = out.File
	file_usage_v1_usage_proto_goTypes = nil
	file_usage_v1_usage_proto_depIdxs = nil
}
