// Routing decisions for "openrouter/auto" and semantic routing (DRD RT-002, RT-009).
// Go gateway delegates to Python when explicit model isn't specified.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: routing/v1/routing.proto

package routingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestedModel string                 `protobuf:"bytes,1,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"` // e.g. "openrouter/auto"
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Hints          *RequestHints          `protobuf:"bytes,3,opt,name=hints,proto3" json:"hints,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveModelRequest) Reset() {
	*x = ResolveModelRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelRequest) ProtoMessage() {}

func (x *ResolveModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelRequest.ProtoReflect.Descriptor instead.
func (*ResolveModelRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveModelRequest) GetRequestedModel() string {
	if x != nil {
		return x.RequestedModel
	}
	return ""
}

func (x *ResolveModelRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ResolveModelRequest) GetHints() *RequestHints {
	if x != nil {
		return x.Hints
	}
	return nil
}

type RequestHints struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	EstimatedInputTokens       uint32                 `protobuf:"varint,1,opt,name=estimated_input_tokens,json=estimatedInputTokens,proto3" json:"estimated_input_tokens,omitempty"`
	NeedsTools                 bool                   `protobuf:"varint,2,opt,name=needs_tools,json=needsTools,proto3" json:"needs_tools,omitempty"`
	NeedsVision                bool                   `protobuf:"varint,3,opt,name=needs_vision,json=needsVision,proto3" json:"needs_vision,omitempty"`
	NeedsStreaming             bool                   `protobuf:"varint,4,opt,name=needs_streaming,json=needsStreaming,proto3" json:"needs_streaming,omitempty"`
	UserGeo                    string                 `protobuf:"bytes,5,opt,name=user_geo,json=userGeo,proto3" json:"user_geo,omitempty"` // ISO country code
	DataResidencyJurisdictions []string               `protobuf:"bytes,6,rep,name=data_residency_jurisdictions,json=dataResidencyJurisdictions,proto3" json:"data_residency_jurisdictions,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RequestHints) Reset() {
	*x = RequestHints{}
	mi := &file_routing_v1_routing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHints) ProtoMessage() {}

func (x *RequestHints) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHints.ProtoReflect.Descriptor instead.
func (*RequestHints) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{1}
}

func (x *RequestHints) GetEstimatedInputTokens() uint32 {
	if x != nil {
		return x.EstimatedInputTokens
	}
	return 0
}

func (x *RequestHints) GetNeedsTools() bool {
	if x != nil {
		return x.NeedsTools
	}
	return false
}

func (x *RequestHints) GetNeedsVision() bool {
	if x != nil {
		return x.NeedsVision
	}
	return false
}

func (x *RequestHints) GetNeedsStreaming() bool {
	if x != nil {
		return x.NeedsStreaming
	}
	return false
}

func (x *RequestHints) GetUserGeo() string {
	if x != nil {
		return x.UserGeo
	}
	return ""
}

func (x *RequestHints) GetDataResidencyJurisdictions() []string {
	if x != nil {
		return x.DataResidencyJurisdictions
	}
	return nil
}

type ResolveModelResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrimaryModel    string                 `protobuf:"bytes,1,opt,name=primary_model,json=primaryModel,proto3" json:"primary_model,omitempty"`
	PrimaryProvider string                 `protobuf:"bytes,2,opt,name=primary_provider,json=primaryProvider,proto3" json:"primary_provider,omitempty"`
	FallbackChain   []*FallbackTarget      `protobuf:"bytes,3,rep,name=fallback_chain,json=fallbackChain,proto3" json:"fallback_chain,omitempty"`
	StrategyUsed    string                 `protobuf:"bytes,4,opt,name=strategy_used,json=strategyUsed,proto3" json:"strategy_used,omitempty"` // cost | latency | quality | semantic
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveModelResponse) Reset() {
	*x = ResolveModelResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveModelResponse) ProtoMessage() {}

func (x *ResolveModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveModelResponse.ProtoReflect.Descriptor instead.
func (*ResolveModelResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveModelResponse) GetPrimaryModel() string {
	if x != nil {
		return x.PrimaryModel
	}
	return ""
}

func (x *ResolveModelResponse) GetPrimaryProvider() string {
	if x != nil {
		return x.PrimaryProvider
	}
	return ""
}

func (x *ResolveModelResponse) GetFallbackChain() []*FallbackTarget {
	if x != nil {
		return x.FallbackChain
	}
	return nil
}

func (x *ResolveModelResponse) GetStrategyUsed() string {
	if x != nil {
		return x.StrategyUsed
	}
	return ""
}

type FallbackTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FallbackTarget) Reset() {
	*x = FallbackTarget{}
	mi := &file_routing_v1_routing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallbackTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallbackTarget) ProtoMessage() {}

func (x *FallbackTarget) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallbackTarget.ProtoReflect.Descriptor instead.
func (*FallbackTarget) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{3}
}

func (x *FallbackTarget) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *FallbackTarget) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ProviderScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []string               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderScoresRequest) Reset() {
	*x = ProviderScoresRequest{}
	mi := &file_routing_v1_routing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderScoresRequest) ProtoMessage() {}

func (x *ProviderScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderScoresRequest.ProtoReflect.Descriptor instead.
func (*ProviderScoresRequest) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderScoresRequest) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

type ProviderScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*ProviderScore       `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderScoresResponse) Reset() {
	*x = ProviderScoresResponse{}
	mi := &file_routing_v1_routing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderScoresResponse) ProtoMessage() {}

func (x *ProviderScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderScoresResponse.ProtoReflect.Descriptor instead.
func (*ProviderScoresResponse) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderScoresResponse) GetScores() []*ProviderScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type ProviderScore struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Model           string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider        string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Score           float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"` // 0..1
	LastUpdatedUnix uint64                 `protobuf:"varint,4,opt,name=last_updated_unix,json=lastUpdatedUnix,proto3" json:"last_updated_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderScore) Reset() {
	*x = ProviderScore{}
	mi := &file_routing_v1_routing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderScore) ProtoMessage() {}

func (x *ProviderScore) ProtoReflect() protoreflect.Message {
	mi := &file_routing_v1_routing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderScore.ProtoReflect.Descriptor instead.
func (*ProviderScore) Descriptor() ([]byte, []int) {
	return file_routing_v1_routing_proto_rawDescGZIP(), []int{6}
}

func (x *ProviderScore) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ProviderScore) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ProviderScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ProviderScore) GetLastUpdatedUnix() uint64 {
	if x != nil {
		return x.LastUpdatedUnix
	}
	return 0
}

var File_routing_v1_routing_proto protoreflect.FileDescriptor

const file_routing_v1_routing_proto_rawDesc = "" +
	"\n" +
	"\x18routing/v1/routing.proto\x12\x15openrouter.routing.v1\"\x90\x01\n" +
	"\x13ResolveModelRequest\x12'\n" +
	"\x0frequested_model\x18\x01 \x01(\tR\x0erequestedModel\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x129\n" +
	"\x05hints\x18\x03 \x01(\v2#.openrouter.routing.v1.RequestHintsR\x05hints\"\x8e\x02\n" +
	"\fRequestHints\x124\n" +
	"\x16estimated_input_tokens\x18\x01 \x01(\rR\x14estimatedInputTokens\x12\x1f\n" +
	"\vneeds_tools\x18\x02 \x01(\bR\n" +
	"needsTools\x12!\n" +
	"\fneeds_vision\x18\x03 \x01(\bR\vneedsVision\x12'\n" +
	"\x0fneeds_streaming\x18\x04 \x01(\bR\x0eneedsStreaming\x12\x19\n" +
	"\buser_geo\x18\x05 \x01(\tR\auserGeo\x12@\n" +
	"\x1cdata_residency_jurisdictions\x18\x06 \x03(\tR\x1adataResidencyJurisdictions\"\xd9\x01\n" +
	"\x14ResolveModelResponse\x12#\n" +
	"\rprimary_model\x18\x01 \x01(\tR\fprimaryModel\x12)\n" +
	"\x10primary_provider\x18\x02 \x01(\tR\x0fprimaryProvider\x12L\n" +
	"\x0efallback_chain\x18\x03 \x03(\v2%.openrouter.routing.v1.FallbackTargetR\rfallbackChain\x12#\n" +
	"\rstrategy_used\x18\x04 \x01(\tR\fstrategyUsed\"B\n" +
	"\x0eFallbackTarget\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"/\n" +
	"\x15ProviderScoresRequest\x12\x16\n" +
	"\x06models\x18\x01 \x03(\tR\x06models\"V\n" +
	"\x16ProviderScoresResponse\x12<\n" +
	"\x06scores\x18\x01 \x03(\v2$.openrouter.routing.v1.ProviderScoreR\x06scores\"\x83\x01\n" +
	"\rProviderScore\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12*\n" +
	"\x11last_updated_unix\x18\x04 \x01(\x04R\x0flastUpdatedUnix2\xe8\x01\n" +
	"\x0eRoutingService\x12g\n" +
	"\fResolveModel\x12*.openrouter.routing.v1.ResolveModelRequest\x1a+.openrouter.routing.v1.ResolveModelResponse\x12m\n" +
	"\x0eProviderScores\x12,.openrouter.routing.v1.ProviderScoresRequest\x1a-.openrouter.routing.v1.ProviderScoresResponseBFZDgithub.com/openrouter/gateway-go/internal/proto/routing/v1;routingv1b\x06proto3"

var (
	file_routing_v1_routing_proto_rawDescOnce sync.Once
	file_routing_v1_routing_proto_rawDescData []byte
)

func file_routing_v1_routing_proto_rawDescGZIP() []byte {
	file_routing_v1_routing_proto_rawDescOnce.Do(func() {
		file_routing_v1_routing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_routing_v1_routing_proto_rawDesc), len(file_routing_v1_routing_proto_rawDesc)))
	})
	return file_routing_v1_routing_proto_rawDescData
}

var file_routing_v1_routing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_routing_v1_routing_proto_goTypes = []any{
	(*ResolveModelRequest)(nil),    // 0: openrouter.routing.v1.ResolveModelRequest
	(*RequestHints)(nil),           // 1: openrouter.routing.v1.RequestHints
	(*ResolveModelResponse)(nil),   // 2: openrouter.routing.v1.ResolveModelResponse
	(*FallbackTarget)(nil),         // 3: openrouter.routing.v1.FallbackTarget
	(*ProviderScoresRequest)(nil),  // 4: openrouter.routing.v1.ProviderScoresRequest
	(*ProviderScoresResponse)(nil), // 5: openrouter.routing.v1.ProviderScoresResponse
	(*ProviderScore)(nil),          // 6: openrouter.routing.v1.ProviderScore
}
var file_routing_v1_routing_proto_depIdxs = []int32{
	1, // 0: openrouter.routing.v1.ResolveModelRequest.hints:type_name -> openrouter.routing.v1.RequestHints
	3, // 1: openrouter.routing.v1.ResolveModelResponse.fallback_chain:type_name -> openrouter.routing.v1.FallbackTarget
	6, // 2: openrouter.routing.v1.ProviderScoresResponse.scores:type_name -> openrouter.routing.v1.ProviderScore
	0, // 3: openrouter.routing.v1.RoutingService.ResolveModel:input_type -> openrouter.routing.v1.ResolveModelRequest
	4, // 4: openrouter.routing.v1.RoutingService.ProviderScores:input_type -> openrouter.routing.v1.ProviderScoresRequest
	2, // 5: openrouter.routing.v1.RoutingService.ResolveModel:output_type -> openrouter.routing.v1.ResolveModelResponse
	5, // 6: openrouter.routing.v1.RoutingService.ProviderScores:output_type -> openrouter.routing.v1.ProviderScoresResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_routing_v1_routing_proto_init() }
func file_routing_v1_routing_proto_init() {
	if File_routing_v1_routing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_routing_v1_routing_proto_rawDesc), len(file_routing_v1_routing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_routing_v1_routing_proto_goTypes,
		DependencyIndexes: file_routing_v1_routing_proto_depIdxs,
		MessageInfos:      file_routing_v1_routing_proto_msgTypes,
	}.Build()
	File_routing_v1_routing_proto = out.File
	file_routing_v1_routing_proto_goTypes = nil
	file_routing_v1_routing_proto_depIdxs = nil
}
