// Auth service: Go gateway calls this when its in-process LRU and Redis both miss.
// Source-of-truth for API key metadata is PostgreSQL (Python-owned).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SHA-256 of the bearer token sent by the client. Plaintext key never crosses the wire.
	KeyHash       string `protobuf:"bytes,1,opt,name=key_hash,json=keyHash,proto3" json:"key_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateKeyRequest) Reset() {
	*x = ValidateKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyRequest) ProtoMessage() {}

func (x *ValidateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyRequest.ProtoReflect.Descriptor instead.
func (*ValidateKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateKeyRequest) GetKeyHash() string {
	if x != nil {
		return x.KeyHash
	}
	return ""
}

type ValidateKeyResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Valid            bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	KeyId            string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	OrgId            string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId           string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedModels    []string               `protobuf:"bytes,5,rep,name=allowed_models,json=allowedModels,proto3" json:"allowed_models,omitempty"` // empty == all allowed
	DeniedModels     []string               `protobuf:"bytes,6,rep,name=denied_models,json=deniedModels,proto3" json:"denied_models,omitempty"`
	RateLimit        *RateLimitPolicy       `protobuf:"bytes,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	Budget           *BudgetPolicy          `protobuf:"bytes,8,opt,name=budget,proto3" json:"budget,omitempty"`
	ExpiresAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RevocationReason string                 `protobuf:"bytes,10,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"` // populated only when valid=false
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateKeyResponse) Reset() {
	*x = ValidateKeyResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateKeyResponse) ProtoMessage() {}

func (x *ValidateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateKeyResponse.ProtoReflect.Descriptor instead.
func (*ValidateKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateKeyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ValidateKeyResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ValidateKeyResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateKeyResponse) GetAllowedModels() []string {
	if x != nil {
		return x.AllowedModels
	}
	return nil
}

func (x *ValidateKeyResponse) GetDeniedModels() []string {
	if x != nil {
		return x.DeniedModels
	}
	return nil
}

func (x *ValidateKeyResponse) GetRateLimit() *RateLimitPolicy {
	if x != nil {
		return x.RateLimit
	}
	return nil
}

func (x *ValidateKeyResponse) GetBudget() *BudgetPolicy {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *ValidateKeyResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ValidateKeyResponse) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

type RateLimitPolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerMinute  uint32                 `protobuf:"varint,1,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	TokensPerMinute    uint32                 `protobuf:"varint,2,opt,name=tokens_per_minute,json=tokensPerMinute,proto3" json:"tokens_per_minute,omitempty"`
	ConcurrentRequests uint32                 `protobuf:"varint,3,opt,name=concurrent_requests,json=concurrentRequests,proto3" json:"concurrent_requests,omitempty"`
	RequestsPerDay     uint32                 `protobuf:"varint,4,opt,name=requests_per_day,json=requestsPerDay,proto3" json:"requests_per_day,omitempty"`
	BurstMultiplier    uint32                 `protobuf:"varint,5,opt,name=burst_multiplier,json=burstMultiplier,proto3" json:"burst_multiplier,omitempty"` // DRD RL-005
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RateLimitPolicy) Reset() {
	*x = RateLimitPolicy{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitPolicy) ProtoMessage() {}

func (x *RateLimitPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitPolicy.ProtoReflect.Descriptor instead.
func (*RateLimitPolicy) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RateLimitPolicy) GetRequestsPerMinute() uint32 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *RateLimitPolicy) GetTokensPerMinute() uint32 {
	if x != nil {
		return x.TokensPerMinute
	}
	return 0
}

func (x *RateLimitPolicy) GetConcurrentRequests() uint32 {
	if x != nil {
		return x.ConcurrentRequests
	}
	return 0
}

func (x *RateLimitPolicy) GetRequestsPerDay() uint32 {
	if x != nil {
		return x.RequestsPerDay
	}
	return 0
}

func (x *RateLimitPolicy) GetBurstMultiplier() uint32 {
	if x != nil {
		return x.BurstMultiplier
	}
	return 0
}

type BudgetPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RemainingCredits float64                `protobuf:"fixed64,1,opt,name=remaining_credits,json=remainingCredits,proto3" json:"remaining_credits,omitempty"` // dollars
	DailyCap         float64                `protobuf:"fixed64,2,opt,name=daily_cap,json=dailyCap,proto3" json:"daily_cap,omitempty"`
	MonthlyCap       float64                `protobuf:"fixed64,3,opt,name=monthly_cap,json=monthlyCap,proto3" json:"monthly_cap,omitempty"`
	HardStop         bool                   `protobuf:"varint,4,opt,name=hard_stop,json=hardStop,proto3" json:"hard_stop,omitempty"` // reject vs warn
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BudgetPolicy) Reset() {
	*x = BudgetPolicy{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetPolicy) ProtoMessage() {}

func (x *BudgetPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetPolicy.ProtoReflect.Descriptor instead.
func (*BudgetPolicy) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetPolicy) GetRemainingCredits() float64 {
	if x != nil {
		return x.RemainingCredits
	}
	return 0
}

func (x *BudgetPolicy) GetDailyCap() float64 {
	if x != nil {
		return x.DailyCap
	}
	return 0
}

func (x *BudgetPolicy) GetMonthlyCap() float64 {
	if x != nil {
		return x.MonthlyCap
	}
	return 0
}

func (x *BudgetPolicy) GetHardStop() bool {
	if x != nil {
		return x.HardStop
	}
	return false
}

type RevokeKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyRequest) Reset() {
	*x = RevokeKeyRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyRequest) ProtoMessage() {}

func (x *RevokeKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RevokeKeyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeKeyResponse) Reset() {
	*x = RevokeKeyResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeKeyResponse) ProtoMessage() {}

func (x *RevokeKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeKeyResponse.ProtoReflect.Descriptor instead.
func (*RevokeKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeKeyResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\x12openrouter.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x12ValidateKeyRequest\x12\x19\n" +
	"\bkey_hash\x18\x01 \x01(\tR\akeyHash\"\xa4\x03\n" +
	"\x13ValidateKeyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12%\n" +
	"\x0eallowed_models\x18\x05 \x03(\tR\rallowedModels\x12#\n" +
	"\rdenied_models\x18\x06 \x03(\tR\fdeniedModels\x12B\n" +
	"\n" +
	"rate_limit\x18\a \x01(\v2#.openrouter.auth.v1.RateLimitPolicyR\trateLimit\x128\n" +
	"\x06budget\x18\b \x01(\v2 .openrouter.auth.v1.BudgetPolicyR\x06budget\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12+\n" +
	"\x11revocation_reason\x18\n" +
	" \x01(\tR\x10revocationReason\"\xf3\x01\n" +
	"\x0fRateLimitPolicy\x12.\n" +
	"\x13requests_per_minute\x18\x01 \x01(\rR\x11requestsPerMinute\x12*\n" +
	"\x11tokens_per_minute\x18\x02 \x01(\rR\x0ftokensPerMinute\x12/\n" +
	"\x13concurrent_requests\x18\x03 \x01(\rR\x12concurrentRequests\x12(\n" +
	"\x10requests_per_day\x18\x04 \x01(\rR\x0erequestsPerDay\x12)\n" +
	"\x10burst_multiplier\x18\x05 \x01(\rR\x0fburstMultiplier\"\x96\x01\n" +
	"\fBudgetPolicy\x12+\n" +
	"\x11remaining_credits\x18\x01 \x01(\x01R\x10remainingCredits\x12\x1b\n" +
	"\tdaily_cap\x18\x02 \x01(\x01R\bdailyCap\x12\x1f\n" +
	"\vmonthly_cap\x18\x03 \x01(\x01R\n" +
	"monthlyCap\x12\x1b\n" +
	"\thard_stop\x18\x04 \x01(\bR\bhardStop\"A\n" +
	"\x10RevokeKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"#\n" +
	"\x11RevokeKeyResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xc7\x01\n" +
	"\vAuthService\x12^\n" +
	"\vValidateKey\x12&.openrouter.auth.v1.ValidateKeyRequest\x1a'.openrouter.auth.v1.ValidateKeyResponse\x12X\n" +
	"\tRevokeKey\x12$.openrouter.auth.v1.RevokeKeyRequest\x1a%.openrouter.auth.v1.RevokeKeyResponseB@Z>github.com/openrouter/gateway-go/internal/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_v1_auth_proto_goTypes = []any{
	(*ValidateKeyRequest)(nil),    // 0: openrouter.auth.v1.ValidateKeyRequest
	(*ValidateKeyResponse)(nil),   // 1: openrouter.auth.v1.ValidateKeyResponse
	(*RateLimitPolicy)(nil),       // 2: openrouter.auth.v1.RateLimitPolicy
	(*BudgetPolicy)(nil),          // 3: openrouter.auth.v1.BudgetPolicy
	(*RevokeKeyRequest)(nil),      // 4: openrouter.auth.v1.RevokeKeyRequest
	(*RevokeKeyResponse)(nil),     // 5: openrouter.auth.v1.RevokeKeyResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	2, // 0: openrouter.auth.v1.ValidateKeyResponse.rate_limit:type_name -> openrouter.auth.v1.RateLimitPolicy
	3, // 1: openrouter.auth.v1.ValidateKeyResponse.budget:type_name -> openrouter.auth.v1.BudgetPolicy
	6, // 2: openrouter.auth.v1.ValidateKeyResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: openrouter.auth.v1.AuthService.ValidateKey:input_type -> openrouter.auth.v1.ValidateKeyRequest
	4, // 4: openrouter.auth.v1.AuthService.RevokeKey:input_type -> openrouter.auth.v1.RevokeKeyRequest
	1, // 5: openrouter.auth.v1.AuthService.ValidateKey:output_type -> openrouter.auth.v1.ValidateKeyResponse
	5, // 6: openrouter.auth.v1.AuthService.RevokeKey:output_type -> openrouter.auth.v1.RevokeKeyResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
