apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-python
  labels:
    app.kubernetes.io/name: backend-python
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-python
